### ISSUE TITLE
return the original ranges params if the intersection is null

### ISSUE THREAD

**Issue by verymuch** [hampusohlsson/intersecting-ranges#1]
Hi, I had taken a try with this. But I found that the function return the original ranges params if the intersection is null. 
For example:

input is as follow:
```
const ranges = [
      [1, 31],  // pink
      [35, 39]
]
```

output：
```
[
      [1, 31],  // pink
      [35, 39]
]
```

Perhaps, the output should be `[]` when no intersections.

**Comment by hampusohlsson** [comment]
Hey @verymuch thanks for the suggestion. Check out the latest version and it should be fixed!
